// lib/dishes.ts

export type Dish = {
  id: string;
  title: string;
  region: string;
  tagline: string;
  rarity: string;
  image: string;
  description?: string[];
  ingredients?: string[];
  steps?: string[];
};

export const DISHES: Dish[] = [
  // --- Core dishes yang sudah punya resep penuh ---
  {
    id: "rendang",
    title: "Rendang Padang",
    region: "West Sumatra",
    tagline: "Slow-cooked beef in coconut milk and spices.",
    rarity: "Rare dish",
    image: "/images/rendang.jpg",
  },
  {
    id: "nasigoreng",
    title: "Nasi Goreng Jawa",
    region: "Java",
    tagline: "Late-night fried rice with egg and sweet soy.",
    rarity: "Everyday favorite",
    image: "/images/nasigoreng.jpg",
  },
  {
    id: "sotoayam",
    title: "Soto Ayam",
    region: "Java",
    tagline: "Bright yellow chicken soup with noodles.",
    rarity: "Comfort food",
    image: "/images/sotoayam.jpg",
  },
  {
    id: "rawon",
    title: "Rawon Surabaya",
    region: "East Java",
    tagline: "Black beef soup with keluak.",
    rarity: "Regional classic",
    image: "/images/rawon.jpg",
  },
  {
    id: "cotomakassar",
    title: "Coto Makassar",
    region: "South Sulawesi",
    tagline: "Rich beef and offal soup with ground peanuts.",
    rarity: "Local legend",
    image: "/images/coto.jpg",
  },
  {
    id: "gudeg",
    title: "Gudeg Jogja",
    region: "Yogyakarta",
    tagline: "Sweet young jackfruit stew in coconut milk.",
    rarity: "Slow-cooked specialty",
    image: "/images/gudeg.jpeg",
  },
  {
    id: "pempek",
    title: "Pempek Palembang",
    region: "South Sumatra",
    tagline: "Fried fishcakes with tangy cuko sauce.",
    rarity: "Street food icon",
    image: "/images/pempek.jpg",
  },

  // --- Nasi / rice dishes ---
  {
    id: "nasi-goreng",
    title: "Nasi Goreng",
    region: "Indonesia",
    tagline: "Indonesian-style fried rice with egg and veggies.",
    rarity: "Everyday favorite",
    image: "/images/placeholder.jpg",
  },
  {
    id: "nasi-goreng-kampung",
    title: "Nasi Goreng Kampung",
    region: "Java",
    tagline: "Rustic fried rice with anchovies and chili.",
    rarity: "Everyday favorite",
    image: "/images/placeholder.jpg",
  },
  {
    id: "nasi-uduk-betawi",
    title: "Nasi Uduk Betawi",
    region: "Jakarta",
    tagline: "Coconut rice with side dishes and sambal.",
    rarity: "Breakfast classic",
    image: "/images/placeholder.jpg",
  },
  {
    id: "nasi-kuning",
    title: "Nasi Kuning",
    region: "Indonesia",
    tagline: "Turmeric rice for celebrations and special days.",
    rarity: "Festive dish",
    image: "/images/placeholder.jpg",
  },
  {
    id: "nasi-liwet-solo",
    title: "Nasi Liwet Solo",
    region: "Central Java",
    tagline: "Savory coconut rice with shredded chicken.",
    rarity: "Regional favorite",
    image: "/images/placeholder.jpg",
  },
  {
    id: "nasi-liwet-sunda",
    title: "Nasi Liwet Sunda",
    region: "West Java",
    tagline: "Rice cooked with anchovies, chili, and spices.",
    rarity: "Comfort food",
    image: "/images/placeholder.jpg",
  },
  {
    id: "nasi-padang",
    title: "Nasi Padang",
    region: "West Sumatra",
    tagline: "Rice with a full spread of Padang curries.",
    rarity: "Iconic feast",
    image: "/images/placeholder.jpg",
  },
  {
    id: "nasi-pecel",
    title: "Nasi Pecel",
    region: "Java",
    tagline: "Rice with blanched veggies and peanut sauce.",
    rarity: "Everyday favorite",
    image: "/images/placeholder.jpg",
  },
  {
    id: "nasi-campur-bali",
    title: "Nasi Campur Bali",
    region: "Bali",
    tagline: "Mixed rice with lawar, sate, and sambal matah.",
    rarity: "Regional classic",
    image: "/images/placeholder.jpg",
  },
  {
    id: "nasi-bebek-madura",
    title: "Nasi Bebek Madura",
    region: "Madura",
    tagline: "Crispy fried duck with sambal and rice.",
    rarity: "Spicy favorite",
    image: "/images/placeholder.jpg",
  },
  {
    id: "nasi-rawon",
    title: "Nasi Rawon",
    region: "East Java",
    tagline: "Rice served with black keluak beef soup.",
    rarity: "Regional favorite",
    image: "/images/placeholder.jpg",
  },
  {
    id: "nasi-gudeg",
    title: "Nasi Gudeg",
    region: "Yogyakarta",
    tagline: "Gudeg with rice, egg, and krecek.",
    rarity: "Regional classic",
    image: "/images/placeholder.jpg",
  },
  {
    id: "lontong-sayur",
    title: "Lontong Sayur",
    region: "Indonesia",
    tagline: "Rice cakes in coconut vegetable curry.",
    rarity: "Breakfast classic",
    image: "/images/placeholder.jpg",
  },
  {
    id: "lontong-cap-go-meh",
    title: "Lontong Cap Go Meh",
    region: "Java",
    tagline: "Festive lontong with rich sides for Cap Go Meh.",
    rarity: "Festive dish",
    image: "/images/placeholder.jpg",
  },
  {
    id: "lontong-balap",
    title: "Lontong Balap",
    region: "Surabaya",
    tagline: "Lontong with beansprouts, tofu, and lentho.",
    rarity: "Street food",
    image: "/images/placeholder.jpg",
  },

  // --- Soto / soup / kuah ---
  {
    id: "soto-betawi",
    title: "Soto Betawi",
    region: "Jakarta",
    tagline: "Creamy beef soup with coconut milk.",
    rarity: "Comfort food",
    image: "/images/placeholder.jpg",
  },
  {
    id: "soto-lamongan",
    title: "Soto Lamongan",
    region: "East Java",
    tagline: "Yellow chicken soup with koya topping.",
    rarity: "Everyday favorite",
    image: "/images/placeholder.jpg",
  },
  {
    id: "soto-banjar",
    title: "Soto Banjar",
    region: "South Kalimantan",
    tagline: "Chicken soup with spices and rice cakes.",
    rarity: "Regional favorite",
    image: "/images/placeholder.jpg",
  },
  {
    id: "soto-kudus",
    title: "Soto Kudus",
    region: "Central Java",
    tagline: "Light chicken or buffalo soup in small bowls.",
    rarity: "Regional classic",
    image: "/images/placeholder.jpg",
  },
  {
    id: "coto-makassar-alt",
    title: "Coto Makassar (Alt)",
    region: "South Sulawesi",
    tagline: "Another style of Makassar beef and offal soup.",
    rarity: "Local legend",
    image: "/images/placeholder.jpg",
  },
  {
    id: "sop-konro",
    title: "Sop Konro",
    region: "South Sulawesi",
    tagline: "Spiced beef rib soup, sometimes grilled.",
    rarity: "Rich & hearty",
    image: "/images/placeholder.jpg",
  },
  {
    id: "sop-saudara",
    title: "Sop Saudara",
    region: "South Sulawesi",
    tagline: "Makassar-style beef soup with vermicelli.",
    rarity: "Regional favorite",
    image: "/images/placeholder.jpg",
  },
  {
    id: "sop-buntut",
    title: "Sop Buntut",
    region: "Indonesia",
    tagline: "Oxtail soup with clear, fragrant broth.",
    rarity: "Restaurant classic",
    image: "/images/placeholder.jpg",
  },
  {
    id: "sop-iga-sapi",
    title: "Sop Iga Sapi",
    region: "Indonesia",
    tagline: "Short rib soup with vegetables.",
    rarity: "Comfort food",
    image: "/images/placeholder.jpg",
  },
  {
    id: "ikan-kuah-kuning",
    title: "Ikan Kuah Kuning",
    region: "Eastern Indonesia",
    tagline: "Fish in yellow turmeric broth.",
    rarity: "Regional classic",
    image: "/images/placeholder.jpg",
  },
  {
    id: "ikan-pallumara",
    title: "Ikan Pallumara",
    region: "Sulawesi",
    tagline: "Tangy fish soup with tamarind.",
    rarity: "Regional favorite",
    image: "/images/placeholder.jpg",
  },
  {
    id: "ikan-arsik",
    title: "Ikan Arsik",
    region: "North Sumatra",
    tagline: "Batak-style spiced fish with andaliman.",
    rarity: "Rare dish",
    image: "/images/placeholder.jpg",
  },

  // --- Sate / grilled ---
  {
    id: "sate-ayam-madura",
    title: "Sate Ayam Madura",
    region: "Madura",
    tagline: "Chicken satay with thick peanut sauce.",
    rarity: "Street food icon",
    image: "/images/placeholder.jpg",
  },
  {
    id: "sate-kambing",
    title: "Sate Kambing",
    region: "Java",
    tagline: "Goat satay with sweet soy and chili.",
    rarity: "Weekend favorite",
    image: "/images/placeholder.jpg",
  },
  {
    id: "sate-padang",
    title: "Sate Padang",
    region: "West Sumatra",
    tagline: "Satay with thick spicy yellow gravy.",
    rarity: "Regional classic",
    image: "/images/placeholder.jpg",
  },
  {
    id: "sate-lilit-bali",
    title: "Sate Lilit Bali",
    region: "Bali",
    tagline: "Minced fish satay wrapped around lemongrass.",
    rarity: "Island favorite",
    image: "/images/placeholder.jpg",
  },
  {
    id: "sate-maranggi",
    title: "Sate Maranggi",
    region: "West Java",
    tagline: "Marinated beef satay with sambal kecap.",
    rarity: "Regional favorite",
    image: "/images/placeholder.jpg",
  },
  {
    id: "sate-taichan",
    title: "Sate Taichan",
    region: "Jakarta",
    tagline: "Grilled chicken satay with lime and sambal.",
    rarity: "Modern street food",
    image: "/images/placeholder.jpg",
  },
  {
    id: "ikan-bakar-jimbaran",
    title: "Ikan Bakar Jimbaran",
    region: "Bali",
    tagline: "Grilled fish with Bali-style sambal.",
    rarity: "Beachside classic",
    image: "/images/placeholder.jpg",
  },
  {
    id: "ayam-bakar-taliwang",
    title: "Ayam Bakar Taliwang",
    region: "Lombok",
    tagline: "Spicy grilled chicken from Lombok.",
    rarity: "Spicy favorite",
    image: "/images/placeholder.jpg",
  },
  {
    id: "ayam-bakar-padang",
    title: "Ayam Bakar Padang",
    region: "West Sumatra",
    tagline: "Grilled chicken with Padang spices.",
    rarity: "Regional classic",
    image: "/images/placeholder.jpg",
  },

  // --- Ayam / daging ---
  {
    id: "opor-ayam",
    title: "Opor Ayam",
    region: "Java",
    tagline: "Chicken braised in coconut milk.",
    rarity: "Lebaran classic",
    image: "/images/placeholder.jpg",
  },
  {
    id: "gulai-ayam",
    title: "Gulai Ayam",
    region: "Sumatra",
    tagline: "Chicken curry with rich spices.",
    rarity: "Comfort food",
    image: "/images/placeholder.jpg",
  },
  {
    id: "semur-daging",
    title: "Semur Daging",
    region: "Java",
    tagline: "Beef braised in sweet soy sauce.",
    rarity: "Home-style classic",
    image: "/images/placeholder.jpg",
  },
  {
    id: "tongseng-kambing",
    title: "Tongseng Kambing",
    region: "Java",
    tagline: "Spicy goat stew with cabbage and tomatoes.",
    rarity: "Street food",
    image: "/images/placeholder.jpg",
  },
  {
    id: "ayam-betutu",
    title: "Ayam Betutu",
    region: "Bali",
    tagline: "Slow-cooked spiced chicken wrapped in banana leaves.",
    rarity: "Ceremonial dish",
    image: "/images/placeholder.jpg",
  },
  {
    id: "ayam-woku",
    title: "Ayam Woku",
    region: "North Sulawesi",
    tagline: "Chicken cooked with vibrant herbs and chili.",
    rarity: "Regional favorite",
    image: "/images/placeholder.jpg",
  },
  {
    id: "ayam-rica-rica",
    title: "Ayam Rica-Rica",
    region: "Manado",
    tagline: "Chicken with fiery chili and tomato sambal.",
    rarity: "Spicy favorite",
    image: "/images/placeholder.jpg",
  },
  {
    id: "ayam-kalasan",
    title: "Ayam Kalasan",
    region: "Yogyakarta",
    tagline: "Fried chicken marinated with coconut and spices.",
    rarity: "Family favorite",
    image: "/images/placeholder.jpg",
  },
  {
    id: "ayam-goreng-mentega",
    title: "Ayam Goreng Mentega",
    region: "Jakarta",
    tagline: "Chinese-Indonesian style butter fried chicken.",
    rarity: "Restaurant classic",
    image: "/images/placeholder.jpg",
  },

  // --- Ikan & seafood ---
  {
    id: "pepes-ikan",
    title: "Pepes Ikan",
    region: "Java",
    tagline: "Steamed fish in banana leaves with spices.",
    rarity: "Home-style favorite",
    image: "/images/placeholder.jpg",
  },
  {
    id: "ikan-woku-belanga",
    title: "Ikan Woku Belanga",
    region: "North Sulawesi",
    tagline: "Fish in spicy woku sauce cooked in a pot.",
    rarity: "Regional favorite",
    image: "/images/placeholder.jpg",
  },
  {
    id: "ikan-asam-padeh",
    title: "Ikan Asam Padeh",
    region: "West Sumatra",
    tagline: "Sour and spicy fish curry.",
    rarity: "Regional classic",
    image: "/images/placeholder.jpg",
  },
  {
    id: "ikan-bakar-rica",
    title: "Ikan Bakar Rica",
    region: "Sulawesi",
    tagline: "Grilled fish with rica-rica chili.",
    rarity: "Spicy favorite",
    image: "/images/placeholder.jpg",
  },
  {
    id: "udang-balado",
    title: "Udang Balado",
    region: "Sumatra",
    tagline: "Prawns cooked in red chili paste.",
    rarity: "Spicy favorite",
    image: "/images/placeholder.jpg",
  },
  {
    id: "cumi-hitam",
    title: "Cumi Hitam",
    region: "Java",
    tagline: "Squid cooked in its own ink.",
    rarity: "Rich & bold",
    image: "/images/placeholder.jpg",
  },

  // --- Sayur & salad ---
  {
    id: "sayur-asem",
    title: "Sayur Asem",
    region: "Java",
    tagline: "Tamarind-based sour vegetable soup.",
    rarity: "Everyday favorite",
    image: "/images/placeholder.jpg",
  },
  {
    id: "sayur-lodeh",
    title: "Sayur Lodeh",
    region: "Java",
    tagline: "Vegetables stewed in coconut milk.",
    rarity: "Home-style classic",
    image: "/images/placeholder.jpg",
  },
  {
    id: "gado-gado",
    title: "Gado-Gado",
    region: "Java",
    tagline: "Indonesian salad with peanut sauce.",
    rarity: "Everyday favorite",
    image: "/images/placeholder.jpg",
  },
  {
    id: "ketoprak",
    title: "Ketoprak",
    region: "Jakarta",
    tagline: "Rice cake, tofu, and vermicelli with peanut sauce.",
    rarity: "Street food",
    image: "/images/placeholder.jpg",
  },
  {
    id: "lotek",
    title: "Lotek",
    region: "West Java",
    tagline: "Boiled vegetables with sweet peanut sauce.",
    rarity: "Regional salad",
    image: "/images/placeholder.jpg",
  },
  {
    id: "pecel-madiun",
    title: "Pecel Madiun",
    region: "East Java",
    tagline: "Blanched veggies with spicy peanut dressing.",
    rarity: "Regional favorite",
    image: "/images/placeholder.jpg",
  },
  {
    id: "urap-urap",
    title: "Urap-Urap",
    region: "Java",
    tagline: "Vegetables with seasoned grated coconut.",
    rarity: "Side dish",
    image: "/images/placeholder.jpg",
  },
  {
    id: "plecing-kangkung",
    title: "Plecing Kangkung",
    region: "Lombok",
    tagline: "Water spinach with spicy tomato sambal.",
    rarity: "Regional salad",
    image: "/images/placeholder.jpg",
  },

  // --- Street food / noodles / bakso ---
  {
    id: "bakso-malang",
    title: "Bakso Malang",
    region: "Malang",
    tagline: "Meatball soup with tofu and fried dumplings.",
    rarity: "Street food icon",
    image: "/images/placeholder.jpg",
  },
  {
    id: "bakso-solo",
    title: "Bakso Solo",
    region: "Solo",
    tagline: "Clear beef meatball soup from Solo.",
    rarity: "Regional favorite",
    image: "/images/placeholder.jpg",
  },
  {
    id: "mie-ayam",
    title: "Mie Ayam",
    region: "Java",
    tagline: "Egg noodles with seasoned chicken and greens.",
    rarity: "Street food staple",
    image: "/images/placeholder.jpg",
  },
  {
    id: "mie-aceh",
    title: "Mie Aceh",
    region: "Aceh",
    tagline: "Spicy curried noodles with meat or seafood.",
    rarity: "Spicy favorite",
    image: "/images/placeholder.jpg",
  },
  {
    id: "mie-kocok",
    title: "Mie Kocok",
    region: "Bandung",
    tagline: "Noodles with beef tendons and rich broth.",
    rarity: "Regional classic",
    image: "/images/placeholder.jpg",
  },
  {
    id: "mie-celor",
    title: "Mie Celor",
    region: "Palembang",
    tagline: "Thick coconut milk noodle soup with shrimp.",
    rarity: "Regional favorite",
    image: "/images/placeholder.jpg",
  },
  {
    id: "kwetiau-goreng",
    title: "Kwetiau Goreng",
    region: "Indonesia",
    tagline: "Stir-fried flat rice noodles.",
    rarity: "Street food favorite",
    image: "/images/placeholder.jpg",
  },
  {
    id: "kwetiau-siram",
    title: "Kwetiau Siram",
    region: "Indonesia",
    tagline: "Flat rice noodles with thick gravy.",
    rarity: "Comfort food",
    image: "/images/placeholder.jpg",
  },
  {
    id: "siomay-bandung",
    title: "Siomay Bandung",
    region: "Bandung",
    tagline: "Steamed fish dumplings with peanut sauce.",
    rarity: "Street food icon",
    image: "/images/placeholder.jpg",
  },
  {
    id: "batagor",
    title: "Batagor",
    region: "Bandung",
    tagline: "Fried dumplings with peanut sauce.",
    rarity: "Street food icon",
    image: "/images/placeholder.jpg",
  },
  {
    id: "cireng",
    title: "Cireng",
    region: "West Java",
    tagline: "Fried tapioca dough with dipping sauce.",
    rarity: "Snack favorite",
    image: "/images/placeholder.jpg",
  },
  {
    id: "cilok",
    title: "Cilok",
    region: "West Java",
    tagline: "Chewy tapioca balls with peanut sauce.",
    rarity: "Street snack",
    image: "/images/placeholder.jpg",
  },
  {
    id: "seblak",
    title: "Seblak",
    region: "Bandung",
    tagline: "Spicy wet crackers with eggs and toppings.",
    rarity: "Spicy snack",
    image: "/images/placeholder.jpg",
  },

  // --- Tahu / tempe / gorengan ---
  {
    id: "tahu-gejrot",
    title: "Tahu Gejrot",
    region: "Cirebon",
    tagline: "Fried tofu in sweet and spicy vinegar sauce.",
    rarity: "Street food",
    image: "/images/placeholder.jpg",
  },
  {
    id: "tahu-sumedang",
    title: "Tahu Sumedang",
    region: "West Java",
    tagline: "Crispy fried tofu specialty from Sumedang.",
    rarity: "Regional snack",
    image: "/images/placeholder.jpg",
  },
  {
    id: "tahu-isi",
    title: "Tahu Isi",
    region: "Indonesia",
    tagline: "Stuffed fried tofu with vegetables.",
    rarity: "Snack favorite",
    image: "/images/placeholder.jpg",
  },
  {
    id: "tempe-mendoan",
    title: "Tempe Mendoan",
    region: "Central Java",
    tagline: "Half-cooked thin fried tempeh.",
    rarity: "Snack favorite",
    image: "/images/placeholder.jpg",
  },
  {
    id: "tempe-orek",
    title: "Tempe Orek",
    region: "Java",
    tagline: "Sweet and spicy sauteed tempeh.",
    rarity: "Side dish",
    image: "/images/placeholder.jpg",
  },
  {
    id: "perkedel-kentang",
    title: "Perkedel Kentang",
    region: "Indonesia",
    tagline: "Fried mashed potato patties.",
    rarity: "Side dish",
    image: "/images/placeholder.jpg",
  },
  {
    id: "perkedel-jagung",
    title: "Perkedel Jagung",
    region: "Indonesia",
    tagline: "Corn fritters with herbs and spices.",
    rarity: "Snack favorite",
    image: "/images/placeholder.jpg",
  },
  {
    id: "bakwan-sayur",
    title: "Bakwan Sayur",
    region: "Indonesia",
    tagline: "Vegetable fritters served with chili.",
    rarity: "Gorengan classic",
    image: "/images/placeholder.jpg",
  },

  // --- Kue tradisional / snack manis ---
  {
    id: "serabi",
    title: "Serabi",
    region: "Java",
    tagline: "Rice flour pancakes with coconut milk.",
    rarity: "Traditional snack",
    image: "/images/placeholder.jpg",
  },
  {
    id: "klepon",
    title: "Klepon",
    region: "Java",
    tagline: "Glutinous rice balls with palm sugar filling.",
    rarity: "Traditional sweet",
    image: "/images/placeholder.jpg",
  },
  {
    id: "onde-onde",
    title: "Onde-Onde",
    region: "Indonesia",
    tagline: "Sesame balls with mung bean filling.",
    rarity: "Traditional sweet",
    image: "/images/placeholder.jpg",
  },
  {
    id: "kue-lumpur",
    title: "Kue Lumpur",
    region: "Indonesia",
    tagline: "Soft custard-like cake with coconut.",
    rarity: "Snack favorite",
    image: "/images/placeholder.jpg",
  },
  {
    id: "kue-cubit",
    title: "Kue Cubit",
    region: "Jakarta",
    tagline: "Mini street pancakes with toppings.",
    rarity: "Modern snack",
    image: "/images/placeholder.jpg",
  },
  {
    id: "lapis-legit",
    title: "Lapis Legit",
    region: "Indonesia",
    tagline: "Layered spice cake with butter.",
    rarity: "Festive cake",
    image: "/images/placeholder.jpg",
  },
  {
    id: "lemper",
    title: "Lemper",
    region: "Java",
    tagline: "Sticky rice rolls with savory filling.",
    rarity: "Snack classic",
    image: "/images/placeholder.jpg",
  },
  {
    id: "dadar-gulung",
    title: "Dadar Gulung",
    region: "Indonesia",
    tagline: "Pandan crepes with coconut and palm sugar.",
    rarity: "Traditional sweet",
    image: "/images/placeholder.jpg",
  },
  {
    id: "getuk",
    title: "Getuk",
    region: "Java",
    tagline: "Cassava cake with grated coconut.",
    rarity: "Traditional snack",
    image: "/images/placeholder.jpg",
  },
  {
    id: "nagasari",
    title: "Nagasari",
    region: "Indonesia",
    tagline: "Steamed banana and rice flour cake.",
    rarity: "Traditional snack",
    image: "/images/placeholder.jpg",
  },

  // --- Martabak / pastry ---
  {
    id: "martabak-manis",
    title: "Martabak Manis",
    region: "Indonesia",
    tagline: "Thick sweet pancake with various fillings.",
    rarity: "Night snack",
    image: "/images/placeholder.jpg",
  },
  {
    id: "martabak-telur",
    title: "Martabak Telur",
    region: "Indonesia",
    tagline: "Savory stuffed egg and meat pancake.",
    rarity: "Night snack",
    image: "/images/placeholder.jpg",
  },
  {
    id: "risoles",
    title: "Risoles",
    region: "Indonesia",
    tagline: "Fried pastry with ragout filling.",
    rarity: "Snack classic",
    image: "/images/placeholder.jpg",
  },
  {
    id: "pastel",
    title: "Pastel",
    region: "Indonesia",
    tagline: "Fried pastry with vegetables and egg.",
    rarity: "Snack favorite",
    image: "/images/placeholder.jpg",
  },

  // --- Dessert & minuman ---
  {
    id: "es-cendol",
    title: "Es Cendol / Dawet",
    region: "Indonesia",
    tagline: "Iced drink with rice flour jelly and coconut milk.",
    rarity: "Dessert drink",
    image: "/images/placeholder.jpg",
  },
  {
    id: "es-doger",
    title: "Es Doger",
    region: "West Java",
    tagline: "Coconut milk shaved ice with toppings.",
    rarity: "Dessert drink",
    image: "/images/placeholder.jpg",
  },
  {
    id: "es-teler",
    title: "Es Teler",
    region: "Indonesia",
    tagline: "Mixed fruit dessert with coconut milk.",
    rarity: "Dessert bowl",
    image: "/images/placeholder.jpg",
  },
  {
    id: "es-campur",
    title: "Es Campur",
    region: "Indonesia",
    tagline: "Mixed shaved ice dessert with various fillings.",
    rarity: "Dessert bowl",
    image: "/images/placeholder.jpg",
  },
  {
    id: "kolak-pisang",
    title: "Kolak Pisang",
    region: "Indonesia",
    tagline: "Banana stewed in coconut milk and palm sugar.",
    rarity: "Ramadan favorite",
    image: "/images/placeholder.jpg",
  },
  {
    id: "kolak-labu",
    title: "Kolak Labu",
    region: "Indonesia",
    tagline: "Pumpkin stewed in coconut milk and palm sugar.",
    rarity: "Ramadan favorite",
    image: "/images/placeholder.jpg",
  },
  {
    id: "pisang-goreng",
    title: "Pisang Goreng",
    region: "Indonesia",
    tagline: "Crispy fried banana fritters.",
    rarity: "Snack classic",
    image: "/images/placeholder.jpg",
  },
  {
    id: "ubi-goreng",
    title: "Ubi Goreng",
    region: "Indonesia",
    tagline: "Fried sweet potato fritters.",
    rarity: "Snack classic",
    image: "/images/placeholder.jpg",
  },
];
